[env:esp32c3m1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = COM3
board_build.partitions = huge_app.csv

; This helps find your local libraries (MAX & LSM)
lib_ldf_mode = deep

build_flags = 
    -D ARDUINO_ARCH_ESP32
    -D USE_NIMBLE

; You were missing this section! 
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1